import { auth } from '@clerk/nextjs/server'
import Anthropic from '@anthropic-ai/sdk'
import { Resend } from 'resend'
import { getUserByClerkId } from '@/lib/db/users'
import { getCheckinsByCompany } from '@/lib/db/checkins'
import { createServiceClient } from '@/lib/supabase/server'

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })
const resend = new Resend(process.env.RESEND_API_KEY)

function getCurrentWeek(): string {
  const now = new Date()
  const jan1 = new Date(now.getFullYear(), 0, 1)
  const week = Math.ceil(((now.getTime() - jan1.getTime()) / 86400000 + jan1.getDay() + 1) / 7)
  return `${now.getFullYear()}-W${String(week).padStart(2, '0')}`
}

export async function POST(request: Request): Promise<Response> {
  const { userId } = await auth()
  if (!userId) return Response.json({ error: 'Unauthorized' }, { status: 401 })

  const user = await getUserByClerkId(userId)
  if (!user) return Response.json({ error: 'User not found' }, { status: 404 })

  if (user.role !== 'manager' && user.role !== 'admin') {
    return Response.json({ error: 'Forbidden' }, { status: 403 })
  }

  const { week } = await request.json().catch(() => ({}))
  const targetWeek = week || getCurrentWeek()

  try {
    const checkins = await getCheckinsByCompany(user.company_id, targetWeek)

    if (checkins.length === 0) {
      return Response.json({ error: 'No check-ins found for this week' }, { status: 404 })
    }

    const checkinsText = checkins
      .map(
        (c) =>
          `Team member: ${c.user?.name ?? 'Unknown'}\nMood: ${c.mood ?? '?'}/5 | Energy: ${c.energy ?? '?'}/5 | Workload: ${c.workload ?? '?'}/5\nTranscript: "${c.transcript ?? '(no transcript)'}"`
      )
      .join('\n\n---\n\n')

    const message = await anthropic.messages.create({
      model: 'claude-sonnet-4-6',
      max_tokens: 1500,
      messages: [
        {
          role: 'user',
          content: `You are Tiim, an AI team assistant. Generate a weekly digest email for the manager.

Week: ${targetWeek}
Number of check-ins: ${checkins.length}

Team check-ins:
${checkinsText}

Write a concise, actionable digest with:
1. **Team overview**: average mood/energy/workload with brief interpretation
2. **Highlights**: top wins and accomplishments mentioned
3. **Blockers to address**: challenges that need manager attention
4. **Recommendations**: 2-3 specific actions for the manager this week

Format as clean HTML with <h3> for section headers. Be warm but professional. Keep it under 400 words.`,
        },
      ],
    })

    const content = message.content[0].type === 'text' ? message.content[0].text : ''

    const supabase = await createServiceClient()
    const { data: digest, error: dbError } = await supabase
      .from('ai_digests')
      .upsert(
        {
          manager_id: user.id,
          company_id: user.company_id,
          week: targetWeek,
          content: { html: content, checkin_count: checkins.length },
        },
        { onConflict: 'manager_id,week' }
      )
      .select()
      .single()

    if (dbError) throw new Error(`DB error: ${dbError.message}`)

    await resend.emails.send({
      from: process.env.RESEND_FROM_EMAIL ?? 'onboarding@resend.dev',
      to: user.email,
      subject: `Tiim — Weekly Digest ${targetWeek}`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 24px;">
          <h2 style="color: #6030FF; margin-bottom: 8px;">Weekly Team Digest</h2>
          <p style="color: #4a5565; margin-bottom: 24px;">${targetWeek} · ${checkins.length} check-in${checkins.length !== 1 ? 's' : ''}</p>
          ${content}
          <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0;" />
          <p style="color: #9ca3af; font-size: 12px;">Generated by Tiim · <a href="https://tiim.space" style="color: #6030FF;">tiim.space</a></p>
        </div>
      `,
    })

    return Response.json({ digest, week: targetWeek })
  } catch (err) {
    console.error('[api/digest/generate] POST error:', err)
    return Response.json({ error: 'Internal server error' }, { status: 500 })
  }
}
